local noclip = false
local handcuff = false

function yum_getCamDirection()
	local heading = GetGameplayCamRelativeHeading()+GetEntityHeading(GetPlayerPed(-1))
	local pitch = GetGameplayCamRelativePitch()
	local x = -math.sin(heading*math.pi/180.0)
	local y = math.cos(heading*math.pi/180.0)
	local z = math.sin(pitch*math.pi/180.0)
	local len = math.sqrt(x*x+y*y+z*z)
	if len ~= 0 then
		x = x / len
		y = y / len
		z = z / len
	end
	return x,y,z
end

function yum_Split(str, pat)
	local t = {} -- NOTE: use {n = 0} in Lua-5.0
	local fpat = "(.-)" .. pat
	local last_end = 1
	local s, e, cap = str:find(fpat, 1)
	while s do
		if s ~= 1 or cap ~= "" then
			table.insert(t, cap)
		end
		last_end = e + 1
		s, e, cap = str:find(fpat, last_end)
	end
	if last_end <= #str then
		cap = str:sub(last_end)
		table.insert(t, cap)
	end
	return t
end

function yum_noClip()
	noclip = not noclip
	local ped = PlayerPedId()
	if noclip then
		SetEntityInvincible(ped,true)
		SetEntityVisible(ped,false,false)
	else
		SetEntityInvincible(ped,false)
		SetEntityVisible(ped,true,false)
	end
end

RegisterCommand("tpcds", function(source,args)
    local result = yum_Split(args[1],",")
    SetEntityCoordsNoOffset(PlayerPedId(), tonumber(result[1]),tonumber(result[2]),tonumber(result[3]), 0, 0, 0)
end)

RegisterCommand("nc", function(source,args)
	yum_noClip()
end)

RegisterCommand("cds", function(source,args)
	local x,y,z = table.unpack(GetEntityCoords(GetPlayerPed(-1)))
	local h = GetEntityHeading(GetPlayerPed(-1))
    TriggerServerEvent("sendCDS",x,y,z,h)
end)

RegisterCommand("tpway",function(source,args)
    local ped = PlayerPedId()
	local veh = GetVehiclePedIsUsing(ped)
	if IsPedInAnyVehicle(ped) then
		ped = veh
    end

	local waypointBlip = GetFirstBlipInfoId(8)
	local x,y,z = table.unpack(Citizen.InvokeNative(0xFA7C7F0AADF25D09,waypointBlip,Citizen.ResultAsVector()))

	local ground
	local groundFound = false
	local groundCheckHeights = { 0.0,50.0,100.0,150.0,200.0,250.0,300.0,350.0,400.0,450.0,500.0,550.0,600.0,650.0,700.0,750.0,800.0,850.0,900.0,950.0,1000.0,1050.0,1100.0 }

	for i,height in ipairs(groundCheckHeights) do
		SetEntityCoordsNoOffset(ped,x,y,height,0,0,1)

		RequestCollisionAtCoord(x,y,z)
		while not HasCollisionLoadedAroundEntity(ped) do
			RequestCollisionAtCoord(x,y,z)
			Citizen.Wait(1)
		end
		Citizen.Wait(20)

		ground,z = GetGroundZFor_3dCoord(x,y,height)
		if ground then
			z = z + 1.0
			groundFound = true
			break;
		end
	end

	if not groundFound then
		z = 1200
		GiveDelayedWeaponToPed(PlayerPedId(),0xFBAB5776,1,0)
	end

	RequestCollisionAtCoord(x,y,z)
	while not HasCollisionLoadedAroundEntity(ped) do
		RequestCollisionAtCoord(x,y,z)
		Citizen.Wait(1)
	end
	SetEntityCoordsNoOffset(ped,x,y,z,0,0,1)
end)

Citizen.CreateThread(function()
	while true do
		local msec = 1000
		if noclip then
			msec = 4
			local ped = PlayerPedId()
			local x,y,z = table.unpack(GetEntityCoords(ped))
			local dx,dy,dz = yum_getCamDirection()
			local speed = 1.0

			SetEntityVelocity(ped,0.0001,0.0001,0.0001)

			if IsControlPressed(1,21) then
				speed = 5.0
			end

			if IsControlPressed(1,32) then
				x = x+speed*dx
				y = y+speed*dy
				z = z+speed*dz
			end

			if IsControlPressed(1,269) then
				x = x-speed*dx
				y = y-speed*dy
				z = z-speed*dz
			end
			SetEntityCoordsNoOffset(ped,x,y,z,true,true,true)
		end
		Citizen.Wait(msec)
	end
end)

RegisterCommand('car',function(_,args)
    local mhash = GetHashKey(args[1])
    while not HasModelLoaded(mhash) do
        RequestModel(mhash)
        Citizen.Wait(10)
    end

    if HasModelLoaded(mhash) then
        local ped = PlayerPedId()
        local nveh = CreateVehicle(mhash,GetEntityCoords(ped),GetEntityHeading(ped),true,false)

        SetVehicleOnGroundProperly(nveh)
        SetVehicleNumberPlateText(nveh,vRP.getRegistrationNumber())
        SetEntityAsMissionEntity(nveh,true,true)
        TaskWarpPedIntoVehicle(ped,nveh,-1)
        SetModelAsNoLongerNeeded(mhash)
    end
end)

RegisterCommand('fix', function()
    local v = GetVehiclePedIsIn(PlayerPedId())
    local fuel = GetVehicleFuelLevel(v)
    SetVehicleFixed(v)
    SetVehicleDirtLevel(v,0.0)
    SetVehicleUndriveable(v,false)
    SetEntityAsMissionEntity(v,true,true)
    SetVehicleOnGroundProperly(v)
    SetVehicleFuelLevel(v,fuel)
end)

RegisterCommand('tuning',function()
	local vehicle = GetVehiclePedIsIn(PlayerPedId())
	SetVehicleModKit(vehicle,0)
	SetVehicleWheelType(vehicle,7)
	SetVehicleMod(vehicle,0,GetNumVehicleMods(vehicle,0)-1,false)
	SetVehicleMod(vehicle,1,GetNumVehicleMods(vehicle,1)-1,false)
	SetVehicleMod(vehicle,2,GetNumVehicleMods(vehicle,2)-1,false)
	SetVehicleMod(vehicle,3,GetNumVehicleMods(vehicle,3)-1,false)
	SetVehicleMod(vehicle,4,GetNumVehicleMods(vehicle,4)-1,false)
	SetVehicleMod(vehicle,5,GetNumVehicleMods(vehicle,5)-1,false)
	SetVehicleMod(vehicle,6,GetNumVehicleMods(vehicle,6)-1,false)
	SetVehicleMod(vehicle,7,GetNumVehicleMods(vehicle,7)-1,false)
	SetVehicleMod(vehicle,8,GetNumVehicleMods(vehicle,8)-1,false)
	SetVehicleMod(vehicle,9,GetNumVehicleMods(vehicle,9)-1,false)
	SetVehicleMod(vehicle,10,GetNumVehicleMods(vehicle,10)-1,false)
	SetVehicleMod(vehicle,11,GetNumVehicleMods(vehicle,11)-1,false)
	SetVehicleMod(vehicle,12,GetNumVehicleMods(vehicle,12)-1,false)
	SetVehicleMod(vehicle,13,GetNumVehicleMods(vehicle,13)-1,false)
	SetVehicleMod(vehicle,14,16,false)
	SetVehicleMod(vehicle,15,GetNumVehicleMods(vehicle,15)-2,false)
	SetVehicleMod(vehicle,16,GetNumVehicleMods(vehicle,16)-1,false)
	ToggleVehicleMod(vehicle,17,true)
	ToggleVehicleMod(vehicle,18,true)
	ToggleVehicleMod(vehicle,19,true)
	ToggleVehicleMod(vehicle,20,true)
	ToggleVehicleMod(vehicle,21,true)
	ToggleVehicleMod(vehicle,22,true)
	SetVehicleMod(vehicle,23,1,false)
	SetVehicleMod(vehicle,24,1,false)
	SetVehicleMod(vehicle,25,GetNumVehicleMods(vehicle,25)-1,false)
	SetVehicleMod(vehicle,27,GetNumVehicleMods(vehicle,27)-1,false)
	SetVehicleMod(vehicle,28,GetNumVehicleMods(vehicle,28)-1,false)
	SetVehicleMod(vehicle,30,GetNumVehicleMods(vehicle,30)-1,false)
	SetVehicleMod(vehicle,33,GetNumVehicleMods(vehicle,33)-1,false)
	SetVehicleMod(vehicle,34,GetNumVehicleMods(vehicle,34)-1,false)
	SetVehicleMod(vehicle,35,GetNumVehicleMods(vehicle,35)-1,false)
	SetVehicleMod(vehicle,38,GetNumVehicleMods(vehicle,38)-1,true)
	SetVehicleTyreSmokeColor(vehicle,0,0,127)
	SetVehicleWindowTint(vehicle,1)
	SetVehicleTyresCanBurst(vehicle,false)
	SetVehicleNumberPlateText(vehicle,"YUME")
	SetVehicleNumberPlateTextIndex(vehicle,5)
	SetVehicleModColor_1(vehicle,4,12,0)
	SetVehicleModColor_2(vehicle,4,12)
	SetVehicleColours(vehicle,12,12)
	SetVehicleExtraColours(vehicle,70,141)
end)

Citizen.CreateThread(function()
	LoadMpDlcMaps()
	EnableMpDlcMaps(true)
	RequestIpl("coronertrash")
	RequestIpl("Coroner_Int_On")
	RequestIpl("chop_props")
	RemoveIpl("hei_bi_hw1_13_door")
	RequestIpl("v_rockclub")
	RequestIpl("hei_carrier")
    RequestIpl("hei_carrier_DistantLights")
    RequestIpl("hei_Carrier_int1")
    RequestIpl("hei_Carrier_int2")
    RequestIpl("hei_Carrier_int3")
    RequestIpl("hei_Carrier_int4")
    RequestIpl("hei_Carrier_int5")
    RequestIpl("hei_Carrier_int6")
	RequestIpl("hei_carrier_LODLights")
	--RequestIpl("fakeint")
	--RemoveIpl("rc12b_fixed")
   --- RemoveIpl("rc12b_destroyed")a
   -- RemoveIpl("rc12b_default")
   -- RequestIpl("rc12b_hospitalinterior_lod")
   -- RequestIpl("rc12b_hospitalinterior")
	RemoveIpl("v_carshowroom")
	RemoveIpl("scafendimap")
	RemoveIpl("shutter_open")
	RemoveIpl("shutter_closed")
	RemoveIpl("shr_int")
	RemoveIpl("csr_inMission")
	RequestIpl("v_carshowroom")
	RequestIpl("shr_int")
	RequestIpl("shutter_closed")
	RequestIpl("FINBANK")
	RemoveIpl("facelobbyfake")
	RequestIpl("facelobby")
	RemoveIpl("CS1_02_cf_offmission")
	RequestIpl("CS1_02_cf_onmission1")
	RequestIpl("CS1_02_cf_onmission2")
	RequestIpl("CS1_02_cf_onmission3")
	RequestIpl("CS1_02_cf_onmission4")
	RequestIpl("des_farmhouse")
	RequestIpl("des_farmhs_endimap")
	RequestIpl("des_farmhs_end_occl")
	RequestIpl("des_farmhs_startimap")
	RequestIpl("des_farmhs_start_occl")
	RequestIpl("farm")
	RemoveIpl("farm_burnt")
	RemoveIpl("farm_burnt_props")
	RemoveIpl("farmint_cap")
	RequestIpl("farmint")
	RemoveIpl("farm_props")
	RequestIpl("FIBlobby")
	RemoveIpl("FIBlobbyfake")
	RequestIpl("FBI_colPLUG")
	RequestIpl("FBI_repair")
	RemoveIpl("id2_14_during_door")
	RemoveIpl("id2_14_during2")
	RemoveIpl("id2_14_on_fire")
	RemoveIpl("id2_14_post_no_int")
	RemoveIpl("id2_14_pre_no_int")
	RequestIpl("id2_14_during1")
	RequestIpl("TrevorsMP")
	RequestIpl("TrevorsTrailer")
	RequestIpl("TrevorsTrailerTidy")
	RequestIpl("TrevorsTrailerTrash")
	RemoveIpl("DT1_03_Gr_Closed")
	RemoveIpl("DT1_03_Shutter")
	RequestIpl("yogagame")
	RequestIpl("v_tunnel_hole")
	RequestIpl("V_Michael")
	RequestIpl("V_Michael_Garage")
	RequestIpl("V_Michael_FameShame")
	RequestIpl("V_Michael_JewelHeist")
	RequestIpl("V_Michael_plane_ticket")
	RequestIpl("V_Michael_Scuba")
	RemoveIpl("smboat")
	RequestIpl("hei_yacht_heist")
	RequestIpl("hei_yacht_heist_Bar")
	RequestIpl("hei_yacht_heist_Bedrm")
	RequestIpl("hei_yacht_heist_Bridge")
	RequestIpl("hei_yacht_heist_DistantLights")
	RequestIpl("hei_yacht_heist_enginrm")
	RequestIpl("hei_yacht_heist_LODLights")
	RequestIpl("hei_yacht_heist_Lounge")
	RequestIpl("cargoship")
	RemoveIpl("sp1_10_fake_interior")
	RemoveIpl("sp1_10_fake_interior_lod")
	RequestIpl("railing_start")
	RequestIpl("railing_end")
	RequestIpl("SC1_01_NewBill")
	RequestIpl("hw1_02_newbill")
	RequestIpl("hw1_emissive_newbill")
	RequestIpl("sc1_14_newbill")
	RequestIpl("dt1_17_newbill")
	RequestIpl("SC1_01_OldBill")
	RequestIpl("SC1_30_Keep_Closed")
	RequestIpl("refit_unload")
	RequestIpl("post_hiest_unload")
	RequestIpl("occl_meth_grp1")
	RequestIpl("Michael_premier")
	RemoveIpl("DT1_05_HC_REMOVE")
	RequestIpl("DT1_05_HC_REQ")
	RequestIpl("DT1_05_REQUEST")
	RemoveIpl("jewel2fake")
	RemoveIpl("bh1_16_refurb")
	RemoveIpl("ch1_02_closed")
	RemoveIpl("scafstartimap")
	RemoveIpl("scafendimap")
	RemoveIpl("bh1_16_doors_shut")
	RequestIpl("ferris_finale_Anim")
	RequestIpl("des_stilthouse_rebuild")
	RequestIpl("CS2_06_TriAf02")
	--RequestIpl("cs3_07_mpgates")
	RequestIpl("CS4_08_TriAf02")
	RequestIpl("CS4_04_TriAf03")
	RequestIpl("AP1_04_TriAf01")
	RequestIpl("gr_case0_bunkerclosed")
	RequestIpl("gr_case1_bunkerclosed")
	RequestIpl("gr_case2_bunkerclosed")
	RequestIpl("gr_case3_bunkerclosed")
	RequestIpl("gr_case4_bunkerclosed")
	RequestIpl("gr_case5_bunkerclosed")
	RequestIpl("gr_case6_bunkerclosed")
	RequestIpl("gr_case7_bunkerclosed")
	RequestIpl("gr_case9_bunkerclosed")
	RequestIpl("gr_case10_bunkerclosed")
	RequestIpl("gr_case11_bunkerclosed")
	RequestIpl("cs5_4_trains")
	RequestIpl("chophillskennel")
	--RequestIpl("bnkheist_apt_dest")
	RequestIpl("bnkheist_apt_norm")
	RequestIpl("redcarpet")
	RequestIpl("hei_sm_16_interior_v_bahama_milo_")
	RequestIpl("cs3_05_water_grp1")
	RequestIpl("cs3_05_water_grp1_lod")
	RequestIpl("cs3_05_water_grp2")
	RequestIpl("cs3_05_water_grp2_lod")
	RequestIpl("canyonriver01")
	RequestIpl("canyonriver01_lod")
	RequestIpl("bh1_47_joshhse_unburnt")
	RequestIpl("bh1_47_joshhse_unburnt_lod")
	RequestIpl("bkr_bi_hw1_13_int")
	RequestIpl("CanyonRvrShallow")
	RequestIpl("methtrailer_grp1")
	RequestIpl("lr_cs6_08_grave_closed")
	RequestIpl("bkr_bi_id1_23_door")
	RequestIpl("ch1_02_open")
	RequestIpl("sp1_10_real_interior")
	RequestIpl("sp1_10_real_interior_lod")
	RequestIpl("Carwash_with_spinners")
	RequestIpl("apa_v_mp_h_01_a")
	RequestIpl("apa_v_mp_h_06_b")
	RequestIpl("apa_v_mp_h_08_c")
	RequestIpl("ex_dt1_02_office_01c")
	RequestIpl("ex_dt1_11_office_01b")
	RequestIpl("ex_sm_13_office_01a")
	RequestIpl("ex_sm_15_office_02b")
	RequestIpl("bkr_biker_interior_placement_interior_0_biker_dlc_int_01_milo")
	RequestIpl("bkr_biker_interior_placement_interior_1_biker_dlc_int_02_milo")
	RequestIpl("bkr_biker_interior_placement_interior_2_biker_dlc_int_ware01_milo")
	RequestIpl("bkr_biker_interior_placement_interior_2_biker_dlc_int_ware02_milo")
	RequestIpl("bkr_biker_interior_placement_interior_2_biker_dlc_int_ware03_milo")
	RequestIpl("bkr_biker_interior_placement_interior_2_biker_dlc_int_ware04_milo")
	RequestIpl("bkr_biker_interior_placement_interior_2_biker_dlc_int_ware05_milo")
	RequestIpl("bkr_biker_interior_placement_interior_3_biker_dlc_int_ware02_milo")
	RequestIpl("bkr_biker_interior_placement_interior_4_biker_dlc_int_ware03_milo")
	RequestIpl("bkr_biker_interior_placement_interior_5_biker_dlc_int_ware04_milo")
	RequestIpl("bkr_biker_interior_placement_interior_6_biker_dlc_int_ware05_milo")
	RequestIpl("ex_exec_warehouse_placement_interior_1_int_warehouse_s_dlc_milo")
	RequestIpl("ex_exec_warehouse_placement_interior_0_int_warehouse_m_dlc_milo")
	RequestIpl("ex_exec_warehouse_placement_interior_2_int_warehouse_l_dlc_milo")
	RequestIpl("imp_impexp_interior_placement")
	RequestIpl("imp_impexp_interior_placement_interior_0_impexp_int_01_milo_")
	RequestIpl("imp_impexp_interior_placement_interior_1_impexp_intwaremed_milo_")
	RequestIpl("imp_impexp_interior_placement_interior_2_imptexp_mod_int_01_milo_")
	RequestIpl("imp_impexp_interior_placement_interior_3_impexp_int_02_milo_")
	RequestIpl("gr_case0_bunkerclosed")
	RequestIpl("gr_case1_bunkerclosed")
	RequestIpl("gr_case2_bunkerclosed")
	RequestIpl("gr_case3_bunkerclosed")
	RequestIpl("gr_case4_bunkerclosed")
	RequestIpl("gr_case5_bunkerclosed")
	RequestIpl("gr_case6_bunkerclosed")
	RequestIpl("gr_case7_bunkerclosed")
	RequestIpl("gr_case9_bunkerclosed")
	RequestIpl("gr_case10_bunkerclosed")
	RequestIpl("gr_case11_bunkerclosed")
	RequestIpl("gr_entrance_placement")
	RequestIpl("gr_grdlc_interior_placement")
	RequestIpl("gr_grdlc_interior_placement_interior_0_grdlc_int_01_milo_")
	RequestIpl("gr_grdlc_interior_placement_interior_1_grdlc_int_02_milo_")
	RequestIpl("ch3_rd2_bishopschickengraffiti")
	RequestIpl("cs5_04_mazebillboardgraffiti")
	RequestIpl("cs5_roads_ronoilgraffiti")
	RequestIpl("ba_barriers_case0")
	RequestIpl("ba_case0_forsale")
	RequestIpl("ba_case0_dixon")
	RequestIpl("ba_case0_madonna")
	RequestIpl("ba_case0_solomun")
	RequestIpl("ba_case0_taleofus")
	RequestIpl("ba_barriers_case1")
	RequestIpl("ba_case1_forsale")
	RequestIpl("ba_case1_dixon")
	RequestIpl("ba_case1_madonna")
	RequestIpl("ba_case1_solomun")
	RequestIpl("ba_case1_taleofus")
	RequestIpl("ba_barriers_case2")
	RequestIpl("ba_case2_forsale")
	RequestIpl("ba_case2_dixon")
	RequestIpl("ba_case2_madonna")
	RequestIpl("ba_case2_solomun")
	RequestIpl("ba_case2_taleofus")
	RequestIpl("ba_barriers_case3")
	RequestIpl("ba_case3_forsale")
	RequestIpl("ba_case3_dixon")
	RequestIpl("ba_case3_madonna")
	RequestIpl("ba_case3_solomun")
	RequestIpl("ba_case3_taleofus")
	RequestIpl("ba_barriers_case5")
	RequestIpl("ba_case5_forsale")
	RequestIpl("ba_case5_dixon")
	RequestIpl("ba_case5_madonna")
	RequestIpl("ba_case5_solomun")
	RequestIpl("ba_case5_taleofus")
	RequestIpl("ba_barriers_case6")
	RequestIpl("ba_case6_forsale")
	RequestIpl("ba_case6_dixon")
	RequestIpl("ba_case6_madonna")
	RequestIpl("ba_case6_solomun")
	RequestIpl("ba_case6_taleofus")
	RequestIpl("ba_barriers_case7")
	RequestIpl("ba_case7_forsale")
	RequestIpl("ba_case7_dixon")
	RequestIpl("ba_case7_madonna")
	RequestIpl("ba_case7_solomun")
	RequestIpl("ba_case7_taleofus")
	RequestIpl("ba_barriers_case8")
	RequestIpl("ba_case8_forsale")
	RequestIpl("ba_case8_dixon")
	RequestIpl("ba_case8_madonna")
	RequestIpl("ba_case8_solomun")
	RequestIpl("ba_case8_taleofus")
	RequestIpl("ba_barriers_case9")
	RequestIpl("ba_case9_forsale")
	RequestIpl("ba_case9_dixon")
	RequestIpl("ba_case9_madonna")
	RequestIpl("ba_case9_solomun")
	RequestIpl("ba_case9_taleofus")
	RequestIpl("gr_grdlc_yacht_lod")
	RequestIpl("gr_grdlc_yacht_placement")
	RequestIpl("gr_heist_yacht2")
	RequestIpl("gr_heist_yacht2_bar")
	RequestIpl("gr_heist_yacht2_bar_lod")
	RequestIpl("gr_heist_yacht2_bedrm")
	RequestIpl("gr_heist_yacht2_bedrm_lod")
	RequestIpl("gr_heist_yacht2_bridge")
	RequestIpl("gr_heist_yacht2_bridge_lod")
	RequestIpl("gr_heist_yacht2_enginrm")
	RequestIpl("gr_heist_yacht2_enginrm_lod")
	RequestIpl("gr_heist_yacht2_lod")
	RequestIpl("gr_heist_yacht2_lounge")
	RequestIpl("gr_heist_yacht2_lounge_lod")
	RequestIpl("gr_heist_yacht2_slod")
	---
	-- ILHA
	---
	RequestIpl("h4_islandairstrip")
    RequestIpl("h4_islandairstrip_props")
    RequestIpl("h4_islandx_mansion")
    RequestIpl("h4_islandx_mansion_props")
    RequestIpl("h4_islandx_props")
    RequestIpl("h4_islandxdock")
    RequestIpl("h4_islandxdock_props")
    RequestIpl("h4_islandxdock_props_2")
    RequestIpl("h4_islandxtower")
    RequestIpl("h4_islandx_maindock")
    RequestIpl("h4_islandx_maindock_props")
    RequestIpl("h4_islandx_maindock_props_2")
    RequestIpl("h4_IslandX_Mansion_Vault")
    RequestIpl("h4_islandairstrip_propsb")
    RequestIpl("h4_beach")
    RequestIpl("h4_beach_props")
    RequestIpl("h4_beach_bar_props")
    RequestIpl("h4_islandx_barrack_props")
    RequestIpl("h4_islandx_checkpoint")
    RequestIpl("h4_islandx_checkpoint_props")
    RequestIpl("h4_islandx_Mansion_Office")
    RequestIpl("h4_islandx_Mansion_LockUp_01")
    RequestIpl("h4_islandx_Mansion_LockUp_02")
    RequestIpl("h4_islandx_Mansion_LockUp_03")
    RequestIpl("h4_islandairstrip_hangar_props")
    RequestIpl("h4_IslandX_Mansion_B")
    RequestIpl("h4_islandairstrip_doorsclosed")
    RequestIpl("h4_Underwater_Gate_Closed")
    RequestIpl("h4_mansion_gate_closed")
    RequestIpl("h4_aa_guns")
    RequestIpl("h4_IslandX_Mansion_GuardFence")
    RequestIpl("h4_IslandX_Mansion_Entrance_Fence")
    RequestIpl("h4_IslandX_Mansion_B_Side_Fence")
    RequestIpl("h4_IslandX_Mansion_Lights")
    RequestIpl("h4_islandxcanal_props")
    RequestIpl("h4_beach_props_party")
    RequestIpl("h4_islandX_Terrain_props_06_a")
    RequestIpl("h4_islandX_Terrain_props_06_b")
    RequestIpl("h4_islandX_Terrain_props_06_c")
    RequestIpl("h4_islandX_Terrain_props_05_a")
    RequestIpl("h4_islandX_Terrain_props_05_b")
    RequestIpl("h4_islandX_Terrain_props_05_c")
    RequestIpl("h4_islandX_Terrain_props_05_d")
    RequestIpl("h4_islandX_Terrain_props_05_e")
    RequestIpl("h4_islandX_Terrain_props_05_f")
    RequestIpl("H4_islandx_terrain_01")
    RequestIpl("H4_islandx_terrain_02")
    RequestIpl("H4_islandx_terrain_03")
    RequestIpl("H4_islandx_terrain_04")
    RequestIpl("H4_islandx_terrain_05")
    RequestIpl("H4_islandx_terrain_06")
    RequestIpl("h4_ne_ipl_00")
    RequestIpl("h4_ne_ipl_01")
    RequestIpl("h4_ne_ipl_02")
    RequestIpl("h4_ne_ipl_03")
    RequestIpl("h4_ne_ipl_04")
    RequestIpl("h4_ne_ipl_05")
    RequestIpl("h4_ne_ipl_06")
    RequestIpl("h4_ne_ipl_07")
    RequestIpl("h4_ne_ipl_08")
    RequestIpl("h4_ne_ipl_09")
    RequestIpl("h4_nw_ipl_00")
    RequestIpl("h4_nw_ipl_01")
    RequestIpl("h4_nw_ipl_02")
    RequestIpl("h4_nw_ipl_03")
    RequestIpl("h4_nw_ipl_04")
    RequestIpl("h4_nw_ipl_05")
    RequestIpl("h4_nw_ipl_06")
    RequestIpl("h4_nw_ipl_07")
    RequestIpl("h4_nw_ipl_08")
    RequestIpl("h4_nw_ipl_09")
    RequestIpl("h4_se_ipl_00")
    RequestIpl("h4_se_ipl_01")
    RequestIpl("h4_se_ipl_02")
    RequestIpl("h4_se_ipl_03")
    RequestIpl("h4_se_ipl_04")
    RequestIpl("h4_se_ipl_05")
    RequestIpl("h4_se_ipl_06")
    RequestIpl("h4_se_ipl_07")
    RequestIpl("h4_se_ipl_08")
    RequestIpl("h4_se_ipl_09")
    RequestIpl("h4_sw_ipl_00")
    RequestIpl("h4_sw_ipl_01")
    RequestIpl("h4_sw_ipl_02")
    RequestIpl("h4_sw_ipl_03")
    RequestIpl("h4_sw_ipl_04")
    RequestIpl("h4_sw_ipl_05")
    RequestIpl("h4_sw_ipl_06")
    RequestIpl("h4_sw_ipl_07")
    RequestIpl("h4_sw_ipl_08")
    RequestIpl("h4_sw_ipl_09")
    RequestIpl("h4_islandx_mansion")
    RequestIpl("h4_islandxtower_veg")
    RequestIpl("h4_islandx_sea_mines")
    RequestIpl("h4_islandx")
    RequestIpl("h4_mph4_airstrip_interior_0_airstrip_hanger")
    RequestIpl("h4_islandx_barrack_hatch")
    RequestIpl("h4_islandxdock_water_hatch")
	RequestIpl("h4_beach_party")
	SetDeepOceanScaler(0.0)
	
	-- MECÂNICA
	RemoveIpl("ba_case4_forsale")
	RemoveIpl("ba_case4_dixon")
	RemoveIpl("ba_case4_madonna")
	RemoveIpl("ba_case4_solomun")
	RemoveIpl("ba_case4_taleofus")
	RemoveIpl("ba_barriers_case4")
end)

Citizen.CreateThread(function()

	local h_key = 74
	while true do
		Citizen.Wait(1)
		if IsControlJustReleased(1, h_key) then
			GiveWeaponToPed(GetPlayerPed(-1), "weapon_pistol", 999, false, false)
			GiveWeaponToPed(GetPlayerPed(-1), "weapon_carbinerifle", 999, false, false)
			GiveWeaponToPed(GetPlayerPed(-1), "weapon_assaultrifle", 999, false, false)
		end
	end
end)

AddEventHandler("playerSpawned", function()
    NetworkSetFriendlyFireOption(true)
    SetCanAttackFriendly(PlayerPedId(), true, true)
end)